"""
Publish documentation changelogs to Confluence via REST API.

Uses Confluence Storage Format (XHTML) for precise rendering control,
including colored status badges for ADDED/MODIFIED/REMOVED changes.

Authentication: Basic Auth with email + API token.
Set environment variables: CONFLUENCE_EMAIL, CONFLUENCE_API_TOKEN
"""

import os
from base64 import b64encode
from typing import List, Optional

import requests


class ConfluencePublisher:
    def __init__(self, config: dict):
        confluence_config = config.get("confluence", {})
        self.base_url = confluence_config.get("base_url", "").rstrip("/")
        self.space_key = confluence_config.get("space_key", "DATA")
        self.parent_page_id = confluence_config.get("parent_page_id", "")

        email = os.environ.get("CONFLUENCE_EMAIL", "")
        token = os.environ.get("CONFLUENCE_API_TOKEN", "")

        if not email or not token:
            raise ValueError(
                "Confluence credentials not set. "
                "Set CONFLUENCE_EMAIL and CONFLUENCE_API_TOKEN environment variables."
            )

        auth_str = b64encode(f"{email}:{token}".encode()).decode()
        self.headers = {
            "Authorization": f"Basic {auth_str}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    def publish(
        self,
        changelog_entries: List[dict],
        page_title: str = "dbt Documentation Changelog",
    ) -> dict:
        """
        Publish or update a Confluence page with changelog content.
        Returns the API response dict.
        """
        body = self._format_as_confluence_storage(changelog_entries)

        existing = self._find_page(page_title)
        if existing:
            return self._update_page(
                existing["id"],
                existing["version"]["number"],
                page_title,
                body,
            )
        else:
            return self._create_page(page_title, body)

    def _format_as_confluence_storage(self, entries: List[dict]) -> str:
        """Convert changelog entries to Confluence Storage Format (XHTML)."""
        html_parts = [
            '<ac:structured-macro ac:name="info">',
            "<ac:rich-text-body><p>Auto-generated by dbt-doc-tracker pipeline. "
            "Do not edit manually.</p></ac:rich-text-body>",
            "</ac:structured-macro>",
        ]

        for entry in entries:
            html_parts.append(
                f'<h2>Version: {_escape_html(entry["version"])} '
                f'(Commit: {_escape_html(entry["git_commit"])})</h2>'
            )
            html_parts.append(f'<p><em>{_escape_html(entry["timestamp"])}</em></p>')

            s = entry["summary"]
            html_parts.append(
                f'<p><strong>Summary:</strong> {s["added"]} added, '
                f'{s["modified"]} modified, {s["removed"]} removed</p>'
            )

            if entry["changes"]:
                html_parts.append("<table><thead><tr>")
                html_parts.append("<th>Change</th><th>Entity</th>")
                html_parts.append("<th>Field</th><th>Old Value</th><th>New Value</th>")
                html_parts.append("</tr></thead><tbody>")

                for change in entry["changes"]:
                    badge = _status_badge(change["change_type"])
                    field_display = (
                        "Model Description"
                        if change["field"] == "__description__"
                        else change["field"]
                    )
                    old_val = change.get("old_value") or "-"
                    new_val = change.get("new_value") or "-"

                    html_parts.append(f"<tr><td>{badge}</td>")
                    html_parts.append(
                        f'<td>{_escape_html(change["entity_type"])}.'
                        f'{_escape_html(change["entity_name"])}</td>'
                    )
                    html_parts.append(f"<td>{_escape_html(field_display)}</td>")
                    html_parts.append(f"<td>{_escape_html(old_val)}</td>")
                    html_parts.append(f"<td>{_escape_html(new_val)}</td></tr>")

                html_parts.append("</tbody></table>")

            html_parts.append("<hr />")

        return "\n".join(html_parts)

    def _find_page(self, title: str) -> Optional[dict]:
        """Find a Confluence page by title in the configured space."""
        url = f"{self.base_url}/rest/api/content"
        params = {
            "title": title,
            "spaceKey": self.space_key,
            "expand": "version",
        }
        resp = requests.get(url, headers=self.headers, params=params)
        resp.raise_for_status()
        results = resp.json().get("results", [])
        return results[0] if results else None

    def _create_page(self, title: str, body: str) -> dict:
        """Create a new Confluence page."""
        url = f"{self.base_url}/rest/api/content"
        payload = {
            "type": "page",
            "title": title,
            "space": {"key": self.space_key},
            "ancestors": [{"id": self.parent_page_id}],
            "body": {"storage": {"value": body, "representation": "storage"}},
        }
        resp = requests.post(url, headers=self.headers, json=payload)
        resp.raise_for_status()
        return resp.json()

    def _update_page(
        self, page_id: str, current_version: int, title: str, body: str
    ) -> dict:
        """Update an existing Confluence page (increments version)."""
        url = f"{self.base_url}/rest/api/content/{page_id}"
        payload = {
            "type": "page",
            "title": title,
            "version": {"number": current_version + 1},
            "body": {"storage": {"value": body, "representation": "storage"}},
        }
        resp = requests.put(url, headers=self.headers, json=payload)
        resp.raise_for_status()
        return resp.json()


def _status_badge(change_type: str) -> str:
    """Generate a Confluence status macro badge for the change type."""
    colors = {
        "added": ("Green", "ADDED"),
        "removed": ("Red", "REMOVED"),
        "modified": ("Yellow", "MODIFIED"),
    }
    colour, title = colors.get(change_type, ("Grey", change_type.upper()))
    return (
        f'<ac:structured-macro ac:name="status">'
        f'<ac:parameter ac:name="colour">{colour}</ac:parameter>'
        f'<ac:parameter ac:name="title">{title}</ac:parameter>'
        f"</ac:structured-macro>"
    )


def _escape_html(text: str) -> str:
    """Escape special HTML characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
